package com.gupao.edu.integral.dal.entity;

public class IntegralAccount {
    /**
     * <pre>
     * 
     * 表字段： integral_account.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 用户编号
     * 表字段： integral_account.user_id
     * </pre>
     * 
     */
    private Integer userId;

    /**
     * <pre>
     * 
     * 表字段： integral_account.user_name
     * </pre>
     * 
     */
    private String userName;

    /**
     * <pre>
     * 积分总额
     * 表字段： integral_account.score_balance
     * </pre>
     * 
     */
    private String scoreBalance;

    /**
     * <pre>
     * 可用积分
     * 表字段： integral_account.available_score_balance
     * </pre>
     * 
     */
    private String availableScoreBalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account.id
     *
     * @return the value of integral_account.id
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account.id
     *
     * @param id the value for integral_account.id
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account.user_id
     *
     * @return the value of integral_account.user_id
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account.user_id
     *
     * @param userId the value for integral_account.user_id
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account.user_name
     *
     * @return the value of integral_account.user_name
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account.user_name
     *
     * @param userName the value for integral_account.user_name
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account.score_balance
     *
     * @return the value of integral_account.score_balance
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public String getScoreBalance() {
        return scoreBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account.score_balance
     *
     * @param scoreBalance the value for integral_account.score_balance
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public void setScoreBalance(String scoreBalance) {
        this.scoreBalance = scoreBalance == null ? null : scoreBalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account.available_score_balance
     *
     * @return the value of integral_account.available_score_balance
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public String getAvailableScoreBalance() {
        return availableScoreBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account.available_score_balance
     *
     * @param availableScoreBalance the value for integral_account.available_score_balance
     *
     * @mbg.generated Thu Jan 03 17:21:37 GMT+08:00 2019
     */
    public void setAvailableScoreBalance(String availableScoreBalance) {
        this.availableScoreBalance = availableScoreBalance == null ? null : availableScoreBalance.trim();
    }
}