package com.gupao.edu.integral.dal.entity;

public class IntegralAccountDetail {
    /**
     * <pre>
     * 
     * 表字段： integral_account_detail.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 
     * 表字段： integral_account_detail.user_id
     * </pre>
     * 
     */
    private Integer userId;

    /**
     * <pre>
     * 
     * 表字段： integral_account_detail.integral_account_id
     * </pre>
     * 
     */
    private Integer integralAccountId;

    /**
     * <pre>
     * 操作分值
     * 表字段： integral_account_detail.opration_score
     * </pre>
     * 
     */
    private String oprationScore;

    /**
     * <pre>
     * 可用积分
     * 表字段： integral_account_detail.available_score
     * </pre>
     * 
     */
    private String availableScore;

    /**
     * <pre>
     * 操作类型
     * 表字段： integral_account_detail.opration_type
     * </pre>
     * 
     */
    private String oprationType;

    /**
     * <pre>
     * 积分业务类型
     * 表字段： integral_account_detail.score_type
     * </pre>
     * 
     */
    private String scoreType;

    /**
     * <pre>
     * 积分状态
     * 表字段： integral_account_detail.score_status
     * </pre>
     * 
     */
    private String scoreStatus;

    /**
     * <pre>
     * 积分来源
     * 表字段： integral_account_detail.score_source
     * </pre>
     * 
     */
    private String scoreSource;

    /**
     * <pre>
     * 
     * 表字段： integral_account_detail.is_deleted
     * </pre>
     * 
     */
    private String isDeleted;

    /**
     * <pre>
     * 
     * 表字段： integral_account_detail.gmt_create
     * </pre>
     * 
     */
    private String gmtCreate;

    /**
     * <pre>
     * 
     * 表字段： integral_account_detail.gmt_modify
     * </pre>
     * 
     */
    private String gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.id
     *
     * @return the value of integral_account_detail.id
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.id
     *
     * @param id the value for integral_account_detail.id
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.user_id
     *
     * @return the value of integral_account_detail.user_id
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.user_id
     *
     * @param userId the value for integral_account_detail.user_id
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.integral_account_id
     *
     * @return the value of integral_account_detail.integral_account_id
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public Integer getIntegralAccountId() {
        return integralAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.integral_account_id
     *
     * @param integralAccountId the value for integral_account_detail.integral_account_id
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setIntegralAccountId(Integer integralAccountId) {
        this.integralAccountId = integralAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.opration_score
     *
     * @return the value of integral_account_detail.opration_score
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getOprationScore() {
        return oprationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.opration_score
     *
     * @param oprationScore the value for integral_account_detail.opration_score
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setOprationScore(String oprationScore) {
        this.oprationScore = oprationScore == null ? null : oprationScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.available_score
     *
     * @return the value of integral_account_detail.available_score
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getAvailableScore() {
        return availableScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.available_score
     *
     * @param availableScore the value for integral_account_detail.available_score
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setAvailableScore(String availableScore) {
        this.availableScore = availableScore == null ? null : availableScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.opration_type
     *
     * @return the value of integral_account_detail.opration_type
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getOprationType() {
        return oprationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.opration_type
     *
     * @param oprationType the value for integral_account_detail.opration_type
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setOprationType(String oprationType) {
        this.oprationType = oprationType == null ? null : oprationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.score_type
     *
     * @return the value of integral_account_detail.score_type
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getScoreType() {
        return scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.score_type
     *
     * @param scoreType the value for integral_account_detail.score_type
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setScoreType(String scoreType) {
        this.scoreType = scoreType == null ? null : scoreType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.score_status
     *
     * @return the value of integral_account_detail.score_status
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getScoreStatus() {
        return scoreStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.score_status
     *
     * @param scoreStatus the value for integral_account_detail.score_status
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setScoreStatus(String scoreStatus) {
        this.scoreStatus = scoreStatus == null ? null : scoreStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.score_source
     *
     * @return the value of integral_account_detail.score_source
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getScoreSource() {
        return scoreSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.score_source
     *
     * @param scoreSource the value for integral_account_detail.score_source
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setScoreSource(String scoreSource) {
        this.scoreSource = scoreSource == null ? null : scoreSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.is_deleted
     *
     * @return the value of integral_account_detail.is_deleted
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.is_deleted
     *
     * @param isDeleted the value for integral_account_detail.is_deleted
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.gmt_create
     *
     * @return the value of integral_account_detail.gmt_create
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.gmt_create
     *
     * @param gmtCreate the value for integral_account_detail.gmt_create
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate == null ? null : gmtCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_account_detail.gmt_modify
     *
     * @return the value of integral_account_detail.gmt_modify
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public String getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_account_detail.gmt_modify
     *
     * @param gmtModify the value for integral_account_detail.gmt_modify
     *
     * @mbg.generated Thu Jan 03 17:25:17 GMT+08:00 2019
     */
    public void setGmtModify(String gmtModify) {
        this.gmtModify = gmtModify == null ? null : gmtModify.trim();
    }
}