server:
  port: 8081

spring:
  profiles:
    active: dev

  thymeleaf:
    mode: LEGACYHTML5

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.zcoco: INFO

admin:
  session:
     maximumSessions: 1
     maxSessionsPreventsLogin: false

dubbo:
  zk:
    servers: zookeeper:2181
    group: dubbo-dev
  application:
    owner: mic
