package com.gupao.edu.seckill.vo;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "seckill-activity")
public class SecKillActivity {
    /**
     * <pre>
     * 
     * 表字段： seckill-activity.id
     * </pre>
     * 
     */
    @Id
    private Integer id;

    /**
     * <pre>
     * 秒杀名称
     * 表字段： seckill-activity.seckill_name
     * </pre>
     * 
     */
    @Column(name = "seckill_name")
    private String seckillName;

    /**
     * <pre>
     * 货物名称
     * 表字段： seckill-activity.seckill_goods_name
     * </pre>
     * 
     */
    @Column(name = "seckill_goods_name")
    private String seckillGoodsName;

    /**
     * <pre>
     * 货物数量
     * 表字段： seckill-activity.seckill_goods_num
     * </pre>
     * 
     */
    @Column(name = "seckill_goods_num")
    private Integer seckillGoodsNum;

    /**
     * <pre>
     * 秒杀开始时间
     * 表字段： seckill-activity.seckill_start_time
     * </pre>
     * 
     */
    @Column(name = "seckill_start_time")
    private Date seckillStartTime;

    /**
     * <pre>
     * 秒杀结束时间
     * 表字段： seckill-activity.seckill_end_time
     * </pre>
     * 
     */
    @Column(name = "seckill_end_time")
    private Date seckillEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill-activity.id
     *
     * @return the value of seckill-activity.id
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill-activity.id
     *
     * @param id the value for seckill-activity.id
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill-activity.seckill_name
     *
     * @return the value of seckill-activity.seckill_name
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public String getSeckillName() {
        return seckillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill-activity.seckill_name
     *
     * @param seckillName the value for seckill-activity.seckill_name
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public void setSeckillName(String seckillName) {
        this.seckillName = seckillName == null ? null : seckillName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill-activity.seckill_goods_name
     *
     * @return the value of seckill-activity.seckill_goods_name
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public String getSeckillGoodsName() {
        return seckillGoodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill-activity.seckill_goods_name
     *
     * @param seckillGoodsName the value for seckill-activity.seckill_goods_name
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public void setSeckillGoodsName(String seckillGoodsName) {
        this.seckillGoodsName = seckillGoodsName == null ? null : seckillGoodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill-activity.seckill_goods_num
     *
     * @return the value of seckill-activity.seckill_goods_num
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public Integer getSeckillGoodsNum() {
        return seckillGoodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill-activity.seckill_goods_num
     *
     * @param seckillGoodsNum the value for seckill-activity.seckill_goods_num
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public void setSeckillGoodsNum(Integer seckillGoodsNum) {
        this.seckillGoodsNum = seckillGoodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill-activity.seckill_start_time
     *
     * @return the value of seckill-activity.seckill_start_time
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public Date getSeckillStartTime() {
        return seckillStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill-activity.seckill_start_time
     *
     * @param seckillStartTime the value for seckill-activity.seckill_start_time
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public void setSeckillStartTime(Date seckillStartTime) {
        this.seckillStartTime = seckillStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill-activity.seckill_end_time
     *
     * @return the value of seckill-activity.seckill_end_time
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public Date getSeckillEndTime() {
        return seckillEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill-activity.seckill_end_time
     *
     * @param seckillEndTime the value for seckill-activity.seckill_end_time
     *
     * @mbg.generated Fri Jan 11 14:49:46 GMT+08:00 2019
     */
    public void setSeckillEndTime(Date seckillEndTime) {
        this.seckillEndTime = seckillEndTime;
    }
}