package com.gupao.edu.activity.dal.entity;

import java.util.Date;

public class ActivityAward {
    /**
     * <pre>
     * 
     * 表字段： activity_award.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 奖品名称
     * 表字段： activity_award.award_name
     * </pre>
     * 
     */
    private String awardName;

    /**
     * <pre>
     * 奖品信息(如果是卡券类，则以json格式把卡券编号进行存储)
     * 表字段： activity_award.award_info
     * </pre>
     * 
     */
    private String awardInfo;

    /**
     * <pre>
     * 奖品类型
     * 表字段： activity_award.award_type
     * </pre>
     * 
     */
    private Integer awardType;

    /**
     * <pre>
     * 
     * 表字段： activity_award.create_time
     * </pre>
     * 
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award.id
     *
     * @return the value of activity_award.id
     *
     * @mbg.generated Wed Sep 19 10:12:07 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award.id
     *
     * @param id the value for activity_award.id
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award.award_name
     *
     * @return the value of activity_award.award_name
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award.award_name
     *
     * @param awardName the value for activity_award.award_name
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName == null ? null : awardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award.award_info
     *
     * @return the value of activity_award.award_info
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public String getAwardInfo() {
        return awardInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award.award_info
     *
     * @param awardInfo the value for activity_award.award_info
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public void setAwardInfo(String awardInfo) {
        this.awardInfo = awardInfo == null ? null : awardInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award.award_type
     *
     * @return the value of activity_award.award_type
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public Integer getAwardType() {
        return awardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award.award_type
     *
     * @param awardType the value for activity_award.award_type
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public void setAwardType(Integer awardType) {
        this.awardType = awardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award.create_time
     *
     * @return the value of activity_award.create_time
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award.create_time
     *
     * @param createTime the value for activity_award.create_time
     *
     * @mbg.generated Wed Sep 19 10:12:08 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}