package com.gupao.edu.activity.dal.entity;

import java.util.Date;

public class ActivityAwardItem {
    /**
     * <pre>
     * 
     * 表字段： activity_award_item.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 奖项名称
     * 表字段： activity_award_item.item_name
     * </pre>
     * 
     */
    private String itemName;

    /**
     * <pre>
     * 奖品数量
     * 表字段： activity_award_item.total_num
     * </pre>
     * 
     */
    private Integer totalNum;

    /**
     * <pre>
     * 概率
     * 表字段： activity_award_item.probability
     * </pre>
     * 
     */
    private Float probability;

    /**
     * <pre>
     * 奖项状态（0不可用，1可用）
     * 表字段： activity_award_item.status
     * </pre>
     * 
     */
    private Integer status;

    /**
     * <pre>
     * 每天限制发放数
     * 表字段： activity_award_item.day_total_num
     * </pre>
     * 
     */
    private Integer dayTotalNum;

    /**
     * <pre>
     * 奖项等级
     * 表字段： activity_award_item.level
     * </pre>
     * 
     */
    private Integer level;

    /**
     * <pre>
     * 奖项对应的奖品编号（外键）
     * 表字段： activity_award_item.award_id
     * </pre>
     * 
     */
    private Integer awardId;

    /**
     * <pre>
     * 
     * 表字段： activity_award_item.create_time
     * </pre>
     * 
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.id
     *
     * @return the value of activity_award_item.id
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.id
     *
     * @param id the value for activity_award_item.id
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.item_name
     *
     * @return the value of activity_award_item.item_name
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.item_name
     *
     * @param itemName the value for activity_award_item.item_name
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.total_num
     *
     * @return the value of activity_award_item.total_num
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.total_num
     *
     * @param totalNum the value for activity_award_item.total_num
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.probability
     *
     * @return the value of activity_award_item.probability
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public Float getProbability() {
        return probability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.probability
     *
     * @param probability the value for activity_award_item.probability
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setProbability(Float probability) {
        this.probability = probability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.status
     *
     * @return the value of activity_award_item.status
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.status
     *
     * @param status the value for activity_award_item.status
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.day_total_num
     *
     * @return the value of activity_award_item.day_total_num
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public Integer getDayTotalNum() {
        return dayTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.day_total_num
     *
     * @param dayTotalNum the value for activity_award_item.day_total_num
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setDayTotalNum(Integer dayTotalNum) {
        this.dayTotalNum = dayTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.level
     *
     * @return the value of activity_award_item.level
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.level
     *
     * @param level the value for activity_award_item.level
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.award_id
     *
     * @return the value of activity_award_item.award_id
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public Integer getAwardId() {
        return awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.award_id
     *
     * @param awardId the value for activity_award_item.award_id
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_award_item.create_time
     *
     * @return the value of activity_award_item.create_time
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_award_item.create_time
     *
     * @param createTime the value for activity_award_item.create_time
     *
     * @mbg.generated Wed Sep 19 10:15:43 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}